/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CLK.h
**     Project     : Model_M_Motor_control
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.054, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-01-07, 17:48, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : CLK
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            High pin value means ON                      : yes
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init - void CLK_Init(void);
**         On   - void CLK_On(void);
**         Off  - void CLK_Off(void);
**         Neg  - void CLK_Neg(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     Web: http://mcuoneclipse.com
**     This an open source software implementing an LED driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file CLK.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup CLK_module CLK module documentation
**  @{
*/         

#ifndef __CLK_H
#define __CLK_H

/* MODULE CLK. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin6.h"

#include "Cpu.h"

#define CLK_ClrVal()    LEDpin6_ClrVal() /* put the pin on low level */
#define CLK_SetVal()    LEDpin6_SetVal() /* put the pin on high level */
#define CLK_SetInput()  LEDpin6_SetInput() /* use the pin as input pin */
#define CLK_SetOutput() LEDpin6_SetOutput() /* use the pin as output pin */

#define CLK_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define CLK_On() LEDpin6_SetVal()
/*
** ===================================================================
**     Method      :  CLK_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define CLK_Off() LEDpin6_ClrVal()
/*
** ===================================================================
**     Method      :  CLK_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define CLK_Neg() LEDpin6_NegVal()
/*
** ===================================================================
**     Method      :  CLK_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define CLK_Init() CLK_Off()
/*
** ===================================================================
**     Method      :  CLK_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END CLK. */

#endif
/* ifndef __CLK_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
