/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2C1.c
**     Project     : Model_M_Motor_control
**     Processor   : MKL25Z128VLK4
**     Component   : InternalI2C
**     Version     : Component 01.287, Driver 01.01, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-01-07, 15:26, # CodeGen: 0
**     Abstract    :
**          This component encapsulates the internal I2C communication 
**          interface. The implementation of the interface is based 
**          on the Philips I2C-bus specification version 2.0. 
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible 
**              (see "Automatic stop condition" property)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
**     Settings    :
**          Component name                                 : I2C1
**          I2C_LDD                                        : I2C_LDD
**          I2C channel                                    : I2C0
**          Mode selection                                 : MASTER - SLAVE
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_I2C0
**            Interrupt priority                           : medium priority
**            Buffers for SLAVE mode                       : Enabled
**              Input buffer size                          : 4
**              Output buffer size                         : 4
**          MASTER mode                                    : Enabled
**            Polling trials                               : 2000
**            Automatic stop condition                     : yes
**            Initialization                               : 
**              Address mode                               : 7-bit addressing
**              Target slave address init                  : 8
**          SLAVE mode                                     : Enabled
**            Address mode                                 : 7-bit addressing
**            Slave address                                : 8
**            General call address                         : Disabled
**            Empty character                              : 0
**            Second slave address                         : Disabled
**            Alert response address                       : Disabled
**            Slave baud rate control                      : Disabled
**          Data and Clock                                 : 
**            SDA pin                                      : CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5
**            SDA pin signal                               : 
**            SCL pin                                      : CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4
**            SCL pin signal                               : 
**            High drive select                            : Disabled
**          Internal frequency (multiplier factor)         : 23.986176 MHz
**          Bits 0-2 of Frequency divider register         : 111
**          Bits 3-5 of Frequency divider register         : 011
**          SCL frequency                                  : 99.942 kHz
**          SDA Hold                                       : 1.376 us
**          Noise (glitch) filter                          : 0
**          Low timeout                                    : Disabled
**          Wake-up                                        : Disabled
**          Initialization                                 : 
**            Enabled in init code                         : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : Enabled
**            Low speed mode                               : Disabled
**            Slow speed mode                              : Disabled
**     Contents    :
**         SendBlock   - byte I2C1_SendBlock(void* Ptr, word Siz, word *Snt);
**         RecvBlock   - byte I2C1_RecvBlock(void* Ptr, word Siz, word *Rcv);
**         ClearTxBuf  - byte I2C1_ClearTxBuf(void);
**         ClearRxBuf  - byte I2C1_ClearRxBuf(void);
**         SelectSlave - byte I2C1_SelectSlave(byte Slv);
**         SetMode     - byte I2C1_SetMode(bool MasterMode);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C1.c
** @version 01.01
** @brief
**          This component encapsulates the internal I2C communication 
**          interface. The implementation of the interface is based 
**          on the Philips I2C-bus specification version 2.0. 
**          Interface features:
**          MASTER mode
**            - Multi master communication
**            - The combined format of communication possible 
**              (see "Automatic stop condition" property)
**            - 7-bit slave addressing (10-bit addressing can be made as well)
**            - Acknowledge polling provided
**            - No wait state initiated when a slave device holds the SCL line low
**            - Holding of the SCL line low by slave device recognized as 'not available bus'
**            - Invalid start/stop condition detection provided
**          SLAVE mode
**            - 7-bit slave addressing
**            - General call address detection provided
*/         
/*!
**  @addtogroup I2C1_module I2C1 module documentation
**  @{
*/         


/* MODULE I2C1. */


#include "Events.h"
#include "I2C1.h"

#ifdef __cplusplus
extern "C" {
#endif 

/* SerFlag bits */
#define OVERRUN_ERR      0x01U         /* Overrun error flag bit */
#define WAIT_RX_CHAR     0x02U         /* Wait for received char. flag bit (Master)  */
#define CHAR_IN_TX       0x04U         /* Char is in TX buffer (Master)    */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define IN_PROGRES       0x20U         /* Communication is in progress (Master) */
#define FULL_RX          0x40U         /* Full receive buffer      */
#define MSxSL            0x80U         /* Master x Slave flag bit  */

LDD_TDeviceData *IntI2cLdd1_DeviceDataPtr; /* Device data pointer */
static byte InpLenS;                   /* Length of input buffer's content */
static byte InpPtrRS;                  /* Index for reading from input buffer */
static byte InpPtrWS;                  /* Index for writing to input buffer */
static byte InpBufferS[4];             /* Input buffer I2C communication */
static byte TempBufferReadS;           /* Temporary input buffer I2C communication */
static byte OutLenS;                   /* Length of output bufer's content */
static byte OutPtrRS;                  /* Index for reading from output buffer */
static byte OutPtrWS;                  /* Index for writing to output buffer */
static byte OutBufferS[4];             /* Output buffer for I2C communication */
static byte I2C1_SerFlag;              /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Wait for received char. flag bit (Master) */
                                       /*       2 - Char is in TX buffer (Master) */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Master x Slave */

/*
** ===================================================================
**     Method      :  I2C1_SendBlock (component InternalI2C)
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address bytes
**         inclusive of R/W bit = 0 to the I2C bus and then writes the
**         block of characters to the bus. The slave address must be
**         specified before, by the "SelectSlave" or "SlaveSelect10"
**         method or in component initialization section, "Target slave
**         address init" property. If interrupt service is enabled and
**         the method returns ERR_OK, it doesn't mean that transmission
**         was successful. The state of transmission is detectable by
**         means of events (OnTransmitData, OnError or OnArbitLost).
**         Data to be send is not copied to an internal buffer and
**         remains in the original location. Therefore the content of
**         the buffer should not be changed until the transmission is
**         complete. Event OnTransmitData can be used to detect the end
**         of the transmission.
**         When working as a SLAVE, this method writes a block of
**         characters to the internal output slave buffer and then,
**         after the master starts the communication, to the I2C bus.
**         If no character is ready for a transmission (internal output
**         slave buffer is empty), the "Empty character" will be sent
**         (see "Empty character" property). In SLAVE mode the data are
**         copied to an internal buffer, if specified by "Output buffer
**         size" property.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send.
**         Siz             - Size of the block.
**       * Snt             - Amount of data sent (moved to a buffer).
**                           In master mode, if interrupt support is
**                           enabled, the parameter always returns the
**                           same value as the parameter 'Siz' of this
**                           method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledge (only
**                           in master mode and when interrupt service
**                           is disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot transmit data
**                           ERR_TXFULL - Transmitter is full. Some data
**                           has not been sent. (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in master
**                           mode)
** ===================================================================
*/
byte I2C1_SendBlock(void *Ptr,word Siz,word *Snt)
{
  LDD_TError Error;
  word count;                          /* Number of sent chars */

  if (Siz == 0U) {                     /* Test variable Size on zero */
    *Snt = 0U;
    return ERR_OK;                     /* If zero then OK */
  }
  if (I2C1_SerFlag & MSxSL) {
    EnterCritical();                   /* Enter the critical section */
    Error = IntI2cLdd1_MasterSendBlock(IntI2cLdd1_DeviceDataPtr, (LDD_TData *)Ptr, (LDD_I2C_TSize)Siz, LDD_I2C_SEND_STOP); /* Send one data byte */
    if (Error == ERR_BUSY) {
      ExitCritical();                  /* Exit the critical section */
      return ERR_BUSOFF;
    }
    ExitCritical();                    /* Exit the critical section */
    *Snt = Siz;                        /* Dummy number of really sent chars */
  } else {
    EnterCritical();                   /* Enter the critical section */
    *Snt = 0U;                         /* Return number of sent chars */
    for(count=0U; count < Siz; count++) {
      if (OutLenS < 4U) {              /* Is number of bytes in the transmit buffer lower than size of buffer? */
        OutLenS++;                     /* Increase number of bytes in the transmit buffer */
        OutBufferS[OutPtrWS++] = *((byte *)Ptr + count); /* Store char to buffer */
        if (OutPtrWS >= 4U) {          /* Is the pointer out of the transmit buffer? */
          OutPtrWS = 0U;               /* Set pointer to the first item in the transmit buffer */
        }
        (*Snt)++;                      /* Increment number of sent chars */
      } else {
        ExitCritical();                /* Exit the critical section */
        return ERR_TXFULL;             /* Return with error */
      }
    }
    (void)IntI2cLdd1_SlaveSendBlock(IntI2cLdd1_DeviceDataPtr, (LDD_TData *)&OutBufferS[OutPtrRS], 1U); /* Send data char */
    ExitCritical();                    /* Exit the critical section */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_RecvBlock (component InternalI2C)
**     Description :
**         When working as a MASTER, this method writes one (7-bit
**         addressing) or two (10-bit addressing) slave address bytes
**         inclusive of R/W bit = 1 to the I2C bus, then reads the
**         block of characters from the bus and then sends the stop
**         condition. The slave address must be specified before, by
**         the "SelectSlave" or "SelectSlave10" method or in component
**         initialization section, "Target slave address init" property.
**         If interrupt service is enabled and the method returns
**         ERR_OK, it doesn't mean that transmission was finished
**         successfully. The state of transmission must be tested by
**         means of events (OnReceiveData, OnError or OnArbitLost). In
**         case of successful transmission, received data is ready
**         after OnReceiveData event is called. 
**         When working as a SLAVE, this method reads a block of
**         characters from the input slave buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block space for received
**                           data.
**         Siz             - The size of the block.
**       * Rcv             - Amount of received data. In master mode,
**                           if interrupt support is enabled, the
**                           parameter always returns the same value as
**                           the parameter 'Siz' of this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by an acknowledge (only in
**                           master mode and when interrupt service is
**                           disabled)
**                           ERR_BUSOFF - Clock timeout elapsed or
**                           device cannot receive data
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data. Only
**                           available data (or no data) has been
**                           returned  (slave mode only).
**                           ERR_OVERRUN - Overrun error was detected
**                           from last character or block receiving
**                           (slave mode only)
**                           ERR_ARBITR - Arbitration lost (only when
**                           interrupt service is disabled and in master
**                           mode)
**                           ERR_NOTAVAIL - Method is not available in
**                           current mode - see the comment in the
**                           generated code.
** ===================================================================
*/
byte I2C1_RecvBlock(void* Ptr,word Siz,word *Rcv)
{
  LDD_TError Error;
  word count;                          /* Number of sent chars */
  byte errrc = ERR_OK;                 /* Most serious error */

  if (Siz == 0U) {                     /* Test variable Size on zero */
    *Rcv = 0U;
    return ERR_OK;                     /* If zero then OK */
  }
  if (I2C1_SerFlag & MSxSL) {
    EnterCritical();                   /* Enter the critical section */
    Error = IntI2cLdd1_MasterReceiveBlock(IntI2cLdd1_DeviceDataPtr, (LDD_TData *)Ptr, (LDD_I2C_TSize)Siz, LDD_I2C_SEND_STOP); /* Receive a data block */
    if (Error == ERR_BUSY) {
      ExitCritical();                  /* Exit the critical section */
      return ERR_BUSOFF;
    }
    ExitCritical();                    /* Exit the critical section */
    *Rcv = Siz;                        /* Dummy number of really received chars */
  } else {
    EnterCritical();                   /* Enter the critical section */
    if ((I2C1_SerFlag & (OVERRUN_ERR | FULL_RX)) != 0U) { /* Is the overrun occurred? */
      errrc = ERR_OVERRUN;             /* If yes then return OVERRUN error */
    }
    I2C1_SerFlag &= (uint8_t)~(uint8_t)((OVERRUN_ERR | CHAR_IN_RX | FULL_RX)); /* Clear flag "char in RX buffer" */
    *Rcv = 0U;                         /* Clear number of received chars */
    for (count=0U; count<Siz; count++) {
      if (InpLenS) {                   /* Is number of bytes in the receive buffer lower than size of buffer? */
        InpLenS--;                     /* Decrease number of received chars */
        *((byte *)Ptr + count) = InpBufferS[InpPtrRS++]; /* Read the char */
        if (InpPtrRS >= 4U) {          /* Is the index out of the receive buffer? */
          InpPtrRS = 0U;               /* Set index to the first item into the receive buffer */
        }
        (*Rcv)++;                      /* Increment number of sent chars */
      } else {
        ExitCritical();                /* Exit the critical section */
        if (errrc == ERR_OVERRUN) {
          return ERR_OVERRUN;          /* Return with error */
        } else {
          return ERR_RXEMPTY;          /* Return with error */
        }
      }
    }
    ExitCritical();                    /* Exit the critical section */
    return errrc;                      /* Return error code */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_ClearTxBuf (component InternalI2C)
**     Description :
**         This method clears all characters in internal slave output
**         buffer. This method is not available for the MASTER mode.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte I2C1_ClearTxBuf(void)
{
  EnterCritical();                     /* Enter the critical section */
  OutLenS = 0U;                        /* Set number of chars in the receive buffer to 0 */
  OutPtrRS = 0U;                       /* Set indexes on the first item in the receive buffer */
  OutPtrWS = 0U;
  I2C1_SerFlag &= (uint8_t)~(uint8_t)((FULL_TX|CHAR_IN_TX));
  (void)IntI2cLdd1_SlaveCancelTransmissionBlock(IntI2cLdd1_DeviceDataPtr); /* Cancel transmission block */
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_ClearRxBuf (component InternalI2C)
**     Description :
**         This method clears all characters in internal slave input
**         buffer. This method is not available for the MASTER mode.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte I2C1_ClearRxBuf(void)
{
  EnterCritical();                     /* Enter the critical section */
  InpLenS = 0U;                        /* Set number of chars in the transmit buffer to 0 */
  InpPtrRS = 0U;                       /* Set indexes on the first item in the transmit buffer */
  InpPtrWS = 0U;
  I2C1_SerFlag &= (uint8_t)~(uint8_t)((OVERRUN_ERR | CHAR_IN_RX | FULL_RX));
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_SelectSlave (component InternalI2C)
**     Description :
**         This method selects a new slave for communication by its
**         7-bit slave address value. Any send or receive method
**         directs to or from selected device, until a new slave device
**         is selected by this method. This method is not available for
**         the SLAVE mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Slv             - 7-bit slave address value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_BUSY - The device is busy, wait until
**                           the current operation is finished.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  The device is disabled
** ===================================================================
*/
byte I2C1_SelectSlave(byte Slv)
{
  return (byte)IntI2cLdd1_SelectSlaveDevice(IntI2cLdd1_DeviceDataPtr, LDD_I2C_ADDRTYPE_7BITS, (LDD_I2C_TAddr)(Slv & 0x7FU)); /* Set 7 bits slave device address. */
}

/*
** ===================================================================
**     Method      :  I2C1_SetMode (component InternalI2C)
**     Description :
**         This method sets actual operating mode of this component.
**         This method is available only for the MASTER - SLAVE mode.
**         Note: If MASTER mode is selected as an operating mode, the
**         device can still be selected as a slave and receive/transmit
**         data. However, it's necessary to select slave operating mode
**         using SetMode( FALSE ) to access this data.
**     Parameters  :
**         NAME            - DESCRIPTION
**         MasterMode      - Operating mode value:
**                           TRUE - Master
**                           FALSE - Slave
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte I2C1_SetMode(bool MasterMode)
{
  I2C1_SerFlag &= (uint8_t)~(uint8_t)(MSxSL); /* Set mode */
  I2C1_SerFlag |= (uint8_t)((MasterMode)?MSxSL:0U);
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  I2C1_Init (component InternalI2C)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void I2C1_Init(void)
{
  I2C1_SerFlag = 0x00U;                /* Reset all flags */
  InpLenS = 0U;                        /* No char in the receive buffer */
  InpPtrWS = 0U;                       /* Set indexes on the first item in the receive buffer */
  InpPtrRS = 0U;
  OutLenS = 0U;                        /* No char in the transmit buffer */
  OutPtrWS = 0U;                       /* Set indexes on the first item in the transmit buffer */
  OutPtrRS = 0U;
  IntI2cLdd1_DeviceDataPtr = IntI2cLdd1_Init(NULL); /* Calling init method of the inherited component */
  (void)IntI2cLdd1_SlaveReceiveBlock(IntI2cLdd1_DeviceDataPtr, (LDD_TData *)&TempBufferReadS, 1U); /* Set slave receive data request */
}

/*
** ===================================================================
**     Method      :  I2C1_IntI2cLdd1_OnMasterBlockSent (component InternalI2C)
**
**     Description :
**         This event is called when I2C in master mode finishes the 
**         transmission of the data successfully. This event is not 
**         available for the SLAVE mode and if MasterSendBlock is 
**         disabled.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntI2cLdd1_OnMasterBlockSent(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  I2C1_OnTransmitData();               /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  I2C1_IntI2cLdd1_OnMasterBlockReceived (component InternalI2C)
**
**     Description :
**         This event is called when I2C is in master mode and finishes 
**         the reception of the data successfully. This event is not 
**         available for the SLAVE mode and if MasterReceiveBlock is 
**         disabled.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntI2cLdd1_OnMasterBlockReceived(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  I2C1_OnReceiveData();                /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  I2C1_IntI2cLdd1_OnSlaveBlockSent (component InternalI2C)
**
**     Description :
**         This event is called when I2C in slave mode finishes the 
**         transmission of the data successfully. This event is not 
**         available for the MASTER mode and if SlaveSendBlock is 
**         disabled.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntI2cLdd1_OnSlaveBlockSent(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  if (OutLenS != 0U) {                 /* Is number of bytes in the transmit buffer greater then 0? */
    OutLenS--;                         /* Decrease number of chars in the transmit buffer */
    OutPtrRS++;                        /* Increment read index of the transmit buffer */
    if(OutPtrRS >= 4U) {               /* Is the index out of the transmit buffer? */
      OutPtrRS = 0U;                   /* Set index on the first item into the transmit buffer */
    }
    if (OutLenS != 0U) {               /* Is number of bytes in the transmit buffer greater then 0? */
      (void)IntI2cLdd1_SlaveSendBlock(IntI2cLdd1_DeviceDataPtr, (LDD_TData *)&OutBufferS[OutPtrRS], 1U); /* Send data char */
    }
  }
  I2C1_OnTxChar();                     /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  I2C1_IntI2cLdd1_OnSlaveBlockReceived (component InternalI2C)
**
**     Description :
**         This event is called when I2C in slave mode finishes the 
**         reception of the data successfully. This event is not 
**         available for the MASTER mode and if SlaveReceiveBlock is 
**         disabled.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_FULL_RX    0x01U
#define ON_RX_CHAR    0x02U
#define ON_OVERRUN    0x04U
void IntI2cLdd1_OnSlaveBlockReceived(LDD_TUserData *UserDataPtr)
{
  byte Flags = 0U;                     /* Temporary variable for flags */

  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  (void)IntI2cLdd1_SlaveReceiveBlock(IntI2cLdd1_DeviceDataPtr, (LDD_TData *)&TempBufferReadS, 1U); /* Set slave receive data request */
  if(InpLenS < 4U) {                   /* Is number of bytes in the receive buffer lower than size of buffer? */
    InpLenS++;                         /* Increase number of chars in the receive buffer */
    InpBufferS[InpPtrWS++] = TempBufferReadS; /* Save received char to the receive buffer */
    if(InpPtrWS >= 4U) {               /* Is the index out of the receive buffer? */
      InpPtrWS = 0U;                   /* Set index on the first item into the receive buffer */
    }
    Flags |= ON_RX_CHAR;               /* If yes then set the OnRxChar flag */
    if(InpLenS == 4U) {                /* Is number of bytes in the receive buffer equal to the size of buffer? */
      Flags |= ON_FULL_RX;             /* Set OnFullRxBuf flag */
    }
  } else {
    I2C1_SerFlag |= FULL_RX;           /* Set flag "full RX buffer" */
    Flags |= ON_OVERRUN;               /* Set the OnOverrun flag */
  }
  if((Flags & ON_OVERRUN) != 0U) {     /* Is OnOverrun flag set? */
    I2C1_OnError();                    /* If yes then invoke user event */
  } else {
    if((Flags & ON_RX_CHAR) != 0U) {   /* Is OnRxChar flag set? */
      I2C1_OnRxChar();                 /* If yes then invoke user event */
    }
    if((Flags & ON_FULL_RX) != 0U) {   /* Is OnFullRxBuf flag set? */
      I2C1_OnFullRxBuf();              /* If yes then invoke user event */
    }
  }
}


/* END I2C1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
