/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Rev_Links.h
**     Project     : Model_M_Motor_control
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.054, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-02-12, 12:45, # CodeGen: 69
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : Rev_Links
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            High pin value means ON                      : yes
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void Rev_Links_Init(void);
**         Deinit     - void Rev_Links_Deinit(void);
**         On         - void Rev_Links_On(void);
**         Off        - void Rev_Links_Off(void);
**         Neg        - void Rev_Links_Neg(void);
**         Get        - byte Rev_Links_Get(void);
**         Put        - void Rev_Links_Put(byte val);
**         SetRatio16 - void Rev_Links_SetRatio16(word ratio);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     Web: http://mcuoneclipse.com
**     This an open source software implementing an LED driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Rev_Links.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup Rev_Links_module Rev_Links module documentation
**  @{
*/         

#ifndef __Rev_Links_H
#define __Rev_Links_H

/* MODULE Rev_Links. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin9.h"

#include "Cpu.h"

#define Rev_Links_ClrVal()    LEDpin9_ClrVal() /* put the pin on low level */
#define Rev_Links_SetVal()    LEDpin9_SetVal() /* put the pin on high level */
#define Rev_Links_SetInput()  LEDpin9_SetInput() /* use the pin as input pin */
#define Rev_Links_SetOutput() LEDpin9_SetOutput() /* use the pin as output pin */

#define Rev_Links_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define Rev_Links_On() LEDpin9_SetVal()
/*
** ===================================================================
**     Method      :  Rev_Links_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Rev_Links_Off() LEDpin9_ClrVal()
/*
** ===================================================================
**     Method      :  Rev_Links_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Rev_Links_Neg() LEDpin9_NegVal()
/*
** ===================================================================
**     Method      :  Rev_Links_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Rev_Links_Get() LEDpin9_GetVal()
/*
** ===================================================================
**     Method      :  Rev_Links_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define Rev_Links_Init() Rev_Links_Off()
/*
** ===================================================================
**     Method      :  Rev_Links_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Rev_Links_Put(val)  ((val) ? Rev_Links_On() : Rev_Links_Off())
/*
** ===================================================================
**     Method      :  Rev_Links_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void Rev_Links_Deinit(void);
/*
** ===================================================================
**     Method      :  Rev_Links_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Rev_Links_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  Rev_Links_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END Rev_Links. */

#endif
/* ifndef __Rev_Links_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
