/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Send_OK.h
**     Project     : Model_M_Motor_control
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.054, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-01-07, 17:48, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : Send_OK
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            High pin value means ON                      : yes
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init   - void Send_OK_Init(void);
**         Deinit - void Send_OK_Deinit(void);
**         On     - void Send_OK_On(void);
**         Off    - void Send_OK_Off(void);
**         Neg    - void Send_OK_Neg(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     Web: http://mcuoneclipse.com
**     This an open source software implementing an LED driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Send_OK.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup Send_OK_module Send_OK module documentation
**  @{
*/         

#ifndef __Send_OK_H
#define __Send_OK_H

/* MODULE Send_OK. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin7.h"

#include "Cpu.h"

#define Send_OK_ClrVal()    LEDpin7_ClrVal() /* put the pin on low level */
#define Send_OK_SetVal()    LEDpin7_SetVal() /* put the pin on high level */
#define Send_OK_SetInput()  LEDpin7_SetInput() /* use the pin as input pin */
#define Send_OK_SetOutput() LEDpin7_SetOutput() /* use the pin as output pin */

#define Send_OK_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define Send_OK_On() LEDpin7_SetVal()
/*
** ===================================================================
**     Method      :  Send_OK_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Send_OK_Off() LEDpin7_ClrVal()
/*
** ===================================================================
**     Method      :  Send_OK_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Send_OK_Neg() LEDpin7_NegVal()
/*
** ===================================================================
**     Method      :  Send_OK_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Send_OK_Init() Send_OK_Off()
/*
** ===================================================================
**     Method      :  Send_OK_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Send_OK_Deinit(void);
/*
** ===================================================================
**     Method      :  Send_OK_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END Send_OK. */

#endif
/* ifndef __Send_OK_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
